Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/Weather_Information__c.object-meta.xml
<CustomObject>
    <label>Weather Information</label>
    <nameField>
        <displayFormat>WI-{000000}</displayFormat>
        <label>Weather Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Temperature_Max__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Max__c</fullName>
    <label>Temperature Max</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Temperature_Min__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Min__c</fullName>
    <label>Temperature Min</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Weather_Location__c.field-meta.xml
<CustomField>
    <fullName>Weather_Location__c</fullName>
    <label>Weather Location</label>
    <referenceTo>Weather_Location__c</referenceTo>
    <relationshipLabel>Weather Information</relationshipLabel>
    <relationshipName>Weather_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/Weather_Location__c.object-meta.xml
<CustomObject>
    <label>Weather Location</label>
    <nameField>
        <label>Weather Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/classes/REST_OpenWeatherMap.cls
public class REST_OpenWeatherMap {

    public class APIRequest_weather
    {
        public final mainInfo main;
        public final list<weatherDesc> weather;
    }
    public class mainInfo
    {
        final decimal temp, temp_min, temp_max, pressure, humidity;
    }
    public class weatherDesc
    {
        final String description;
    }
    
    public static void invokeGetWeather(List<Weather_Location__c> Locations)
    {
        system.debug('Prepping Location ids');
        Set<Id> locationIds = new Set<id>();
		for(Weather_Location__c l : locations)
        {
            locationIds.add(l.id);
        }
        REST_getAndRecordWeatherInfo(locationIds);
    }
    
    @future(callout = true)
    public static void REST_getAndRecordWeatherInfo(Set<Id> locationIds) 
    {
        System.debug('REST_getAndRecordWeatherInfo');
        List<Weather_Information__c> weatherdata = new list<Weather_Information__c>();
        Http http = new Http();
        for(Weather_Location__c location : [SELECT Id, Latitude__c,Longitude__c from  Weather_Location__c where Id in : locationIds])
        {
            HttpRequest request = new HttpRequest();
            //Would be best to stick all the endpoint paramaters into a custom setting if there was more time.
            request.setEndpoint('https://api.openweathermap.org/data/2.5/weather?lat='+location.Latitude__c+'&lon='+location.Longitude__c+'&APPID=cc26dbec66aa9b6fbff200b1255e79bd&units=metric');
            request.setMethod('GET');
            HttpResponse response = http.send(request);   
            
            if(response.getStatusCode() == 200)
            {
                APIRequest_weather newWeather = (APIRequest_weather)System.JSON.deserialize(response.getbody(), APIRequest_weather.class);  
                weatherdata.add(new Weather_Information__c(
                    Temperature__c = newWeather.main.temp,
                    Temperature_Max__c = newWeather.main.temp_max,
                    Temperature_Min__c = newWeather.main.temp_min,
                    Humidity__c = newWeather.main.humidity,
                    Pressure__c = newWeather.main.pressure,
                    Weather_Description__c = newWeather.weather[0].description,
                    Weather_Location__c = location.Id
                ));
            }
            //else handle error
        } 
        system.debug(weatherdata);
        
        //try{}catch(exception e){}
        //Error handling normally around here for rollback/feedback but none stated in assignment requirements.
        insert weatherdata;

        system.debug('REST_getAndRecordWeatherInfo - Finish');
    }
}