Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/Weather_Information__c.object-meta.xml
<CustomObject>
    <label>Weather Information</label>
    <nameField>
        <displayFormat>WI-{000000}</displayFormat>
        <label>Weather Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Weather_Location__c.field-meta.xml
<CustomField>
    <fullName>Weather_Location__c</fullName>
    <label>Weather Location</label>
    <referenceTo>Weather_Location__c</referenceTo>
    <relationshipLabel>Weather Information</relationshipLabel>
    <relationshipName>Weather_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/Weather_Location__c.object-meta.xml
<CustomObject>
    <label>Weather Location</label>
    <nameField>
        <label>Weather Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/classes/WeatherLocationTrigger_Test.cls
@isTest
private class WeatherLocationTrigger_Test 
{
    @isTest static void testGetCallout() {
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new OpenWeatherMapHttpCalloutMock()); 
        
        test.startTest();
        Weather_Location__c testLocation = new Weather_Location__c(Name = 'testland', Latitude__c=3.14, Longitude__c=66.01);
        insert testLocation;
        test.stoptest();

        List<Weather_Information__c> weatherInfos = WeatherReporterController.getWeatherReport(testLocation.Id);
        system.assert(weatherInfos.size() == 1);
    }
}