Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/Weather_Information__c.object-meta.xml
<CustomObject>
    <label>Weather Information</label>
    <nameField>
        <displayFormat>WI-{000000}</displayFormat>
        <label>Weather Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Temperature_Max__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Max__c</fullName>
    <label>Temperature Max</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Temperature_Min__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Min__c</fullName>
    <label>Temperature Min</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Information__c/fields/Weather_Location__c.field-meta.xml
<CustomField>
    <fullName>Weather_Location__c</fullName>
    <label>Weather Location</label>
    <referenceTo>Weather_Location__c</referenceTo>
    <relationshipLabel>Weather Information</relationshipLabel>
    <relationshipName>Weather_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Provar Weather Assignment/weather report/force-app/main/default/objects/Weather_Location__c/Weather_Location__c.object-meta.xml
<CustomObject>
    <label>Weather Location</label>
    <nameField>
        <label>Weather Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Provar Weather Assignment/weather report/force-app/main/default/classes/WeatherReporterController.cls
Public without sharing class WeatherReporterController {
    
    @AuraEnabled(cacheable=true)
    public static List<Weather_Information__c> getWeatherReport(String LocationRecordId) 
    {
        List<Weather_Information__c> weatherInfo = 
            [SELECT Id,
             Name,
             Temperature__c,
             Temperature_Max__c,
             Temperature_Min__c,
             Humidity__c,
             Pressure__c,
             Weather_Description__c
             FROM Weather_Information__c 
             WHERE Weather_Location__c =: LocationRecordId 
             ORDER BY createddate DESC 
             LIMIT 1];
        
        return weatherInfo;
    }
}